### PR TITLE
Fix for Issue #9

### PR DESCRIPTION
**Pull request by PramodhN**
Validating that the chosen file is a ZIP file.

### CODE REVIEW

**Comment by erickpeirson** [comment]
@PramodhN, this looks great! Any thoughts on how you could go about testing this?

**Comment by erickpeirson** [comment]
@PramodhN Any updates on this? It has been 9 days... We can merge as soon as there are tests.

**Comment by PramodhN** [comment]
@erickpeirson I'm sorry. Still working on writing the test cases. Been facing a lot of roadblocks while writing them and I thought it would be better to discuss with you in person (on Monday) before proceeding with it.

**Comment by erickpeirson** [comment]
If you're having trouble, let's Skype right away. I'm usually available
throughout the week (sorry I missed you on Wednesday). It would be ideal to
have this wrapped up by Monday, if possible. :-)

--
https://asu.academia.edu/ErickPeirson
Postdoctoral Researcher
Arizona State University

**Pull request merged**
